CREATE TABLE `study_source` (
	`id` varchar(40)  NOT NULL,
	`name` varchar(255)  DEFAULT NULL,
	`no` varchar(255)  DEFAULT NULL,
	`expiretime` bigint(20) DEFAULT 0,
	`resid` varchar(40)  DEFAULT NULL,
	`restype` int(2) DEFAULT 0,
	`categoryid` varchar(40)  DEFAULT NULL,
	`coursewareid` varchar(40)  DEFAULT NULL,
	`descript` varchar(255)  DEFAULT NULL,
	`domainid` varchar(255)  DEFAULT NULL,
	`cover` varchar(255)  DEFAULT NULL,
	`isdel` int(2) DEFAULT 0,
	`length` decimal(19,2) DEFAULT NULL,
	`app` varchar(40)  DEFAULT NULL,
	`openstate` int(2) DEFAULT 2,
	`path` varchar(255)  DEFAULT NULL,
	`released` int(2)  DEFAULT 0,
	`remark` varchar(255)  DEFAULT NULL,
	`score` int DEFAULT 0,
	`sort` int DEFAULT 0,
	`creator` varchar(40)  DEFAULT NULL,
	`createtime` bigint(20) DEFAULT 0,
	`updatetime` bigint(20) DEFAULT 0,
	`updater` varchar(40)  DEFAULT NULL,
	PRIMARY KEY (`id`),
	/*CONSTRAINT `fk_study_source_coursewareid` FOREIGN KEY (`coursewareid`) REFERENCES `study_courseware` (`id`),
	CONSTRAINT `fk_study_source_categoryid` FOREIGN KEY (`categoryid`) REFERENCES `study_course_category` (`id`),*/
	INDEX `idx_study_source_categoryid` USING BTREE (`categoryid`),
	INDEX `idx_study_source_coursewareid` USING BTREE (`coursewareid`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;